kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-shared-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: cns-gold
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

